# Generated by Django 4.2.20 on 2026-03-07 02:50

from django.db import migrations
from django.utils.text import slugify


def create_orgs_for_existing_users(apps, schema_editor):
    """Create organizations for existing users who don't have one."""
    User = apps.get_model('accounts', 'User')
    Organization = apps.get_model('accounts', 'Organization')
    Job = apps.get_model('jobs', 'Job')

    for user in User.objects.filter(organization__isnull=True):
        org_name = user.company or user.username or user.email.split('@')[0]
        base_slug = slugify(org_name) or 'org'
        slug = base_slug
        counter = 1
        while Organization.objects.filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1

        org = Organization.objects.create(
            name=org_name,
            slug=slug,
            max_jobs=5,
            max_resumes_per_job=25,
            max_users=5,
        )

        user.organization = org
        user.role = 'owner'
        user.save(update_fields=['organization', 'role'])

        # Migrate existing jobs to the organization
        Job.objects.filter(created_by=user, organization__isnull=True).update(
            organization=org,
        )


def reverse_migration(apps, schema_editor):
    """No-op reverse — we don't want to delete organizations."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_user_avatar_alter_user_role_and_more'),
        ('jobs', '0003_remove_job_jobs_job_user_id_ec4047_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_orgs_for_existing_users, reverse_migration),
    ]
