# Generated by Django 4.2.20 on 2026-03-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='skillmatch',
            unique_together={('candidate', 'skill_name')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job', 'status'], name='candidates__job_id_46e40d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-overall_score'], name='candidates__overall_38d847_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['-created_at'], name='candidates__created_d94c2e_idx'),
        ),
    ]
