# Generated by Django 4.2.20 on 2026-03-07 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_user_avatar_alter_user_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_job_jobs_job_user_id_ec4047_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_user_id_ec4047_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='education_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_weight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['organization', 'status'], name='jobs_job_organiz_01f5e3_idx'),
        ),
    ]
